[project]
name = "rf-electronics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.2",
]

[dependency-groups]
dev = [
    "ruff>=0.12.11",
]
